### ISSUE TITLE
java.lang.RuntimeException: Render operation failed.

### ISSUE THREAD

**Issue by elhajuojy** [mjfryc/mjaron-etudes-java#21]
**Describe the bug**

when am calling the 
Table.render(books,Book.class).run();
I face the problem of 
java.lang.RuntimeException: Render operation failed.
in my case I want to log table on my console everything was working yesterday but I don't know why I stop working today !!
<img width="1340" alt="Screenshot 2023-09-02 at 12 13 36" src="https://github.com/mjfryc/mjaron-etudes-java/assets/86893073/c0e74679-eba2-4a20-b3ea-2fa8d453c222">

**Comment by elhajuojy** [comment]
i just find the solution in my case in the source class which Book.class the render function access the attrubite
s to the class when i add more attrubites there's a problem in the rundring the the table 

<img width="1312" alt="Screenshot 2023-09-02 at 12 26 28" src="https://github.com/mjfryc/mjaron-etudes-java/assets/86893073/c4273340-490e-4c74-8c6d-0a9abb1652e4">

**Comment by mjfryc** [comment]
Hmm, This library should provide better exception's description. "Render operation failed" is too general of course.
I hope that you've found the solution.
As I understand, there was some private fields, so library couldn't read some fields as java bean.
In next version there will be possibility to read such fields also.
I hope to release it asap.
Regards.
