### ISSUE TITLE
Unable to include using maven please help

### ISSUE THREAD

**Issue by saidarshan27** [mjfryc/mjaron-etudes-java#4]
Hi I am new to maven I am struggling to include your libray using maven please help

**Comment by mjfryc** [comment]
Hi,oh,  sorry, I didn't noticed your post.
Thank you for this issue.
I'm sure that after so long time you've resolved your problem.

Generally, this library is not available in maven central - so I will try to publish it here in few days.

Without maven central - just download `jar` and tell maven to use local `jar`, e.g:
<https://stackoverflow.com/a/3765955/6835932>

Regards,
MJ

**Comment by mjfryc** [comment]
So now this library is available on Maven Central:

<https://search.maven.org/artifact/io.github.mjfryc/mjaron-etudes-java/0.1.11/jar>

```xml
<dependency>
  <groupId>io.github.mjfryc</groupId>
  <artifactId>mjaron-etudes-java</artifactId>
  <version>0.1.11</version>
</dependency>
```

Regards,
MJ
